#! /bin/bash

# Only start in no-sandbox mode on unpriv systems
if grep -q 'Seccomp:	0' /proc/1/status; then
  chromium-browser \
    --ignore-gpu-blocklist \
    --no-first-run \
    --password-store=basic \
    --simulate-outdated-no-au='Tue, 31 Dec 2099 23:59:59 GMT' \
    --start-maximized \
    --user-data-dir > /dev/null 2>&1
else
  chromium-browser \
    --ignore-gpu-blocklist \
    --no-first-run \
    --no-sandbox \
    --password-store=basic \
    --simulate-outdated-no-au='Tue, 31 Dec 2099 23:59:59 GMT' \
    --start-maximized \
    --test-type \
    --user-data-dir > /dev/null 2>&1
fi
